from src.config.default import _CN as cfg

cfg.LOFTR.MATCH_COARSE.MATCH_TYPE = 'dual_softmax'

cfg.TRAINER.CANONICAL_LR = 8e-3
cfg.TRAINER.WARMUP_STEP = 1875  # 3 epochs
cfg.TRAINER.WARMUP_RATIO = 0.1
cfg.TRAINER.MSLR_MILESTONES = [8, 12, 16, 20, 24]

# pose estimation
cfg.TRAINER.RANSAC_PIXEL_THR = 0.5

cfg.TRAINER.OPTIMIZER = "adamw"
cfg.TRAINER.ADAMW_DECAY = 0.1
cfg.LOFTR.MATCH_COARSE.TRAIN_COARSE_PERCENT = 0.3

cfg.FUNDAMENTAL_MATRIX.COMPUTE_FINE = True
cfg.FUNDAMENTAL_MATRIX.ROBUST_ESTIMATOR_TYPE = 'IRLS'
cfg.FUNDAMENTAL_MATRIX.MATRIX_TYPE = 'F'
cfg.FUNDAMENTAL_MATRIX.P = 1.0
