from src.config.default import _CN as cfg

cfg.LOFTR.MATCH_COARSE.MATCH_TYPE = 'dual_softmax'
cfg.LOFTR.MATCH_COARSE.SPARSE_SPVS = False
cfg.LOFTR.MATCH_COARSE.TRAIN_COARSE_PERCENT = 1.0

cfg.TRAINER.SCHEDULER = 'ExponentialLR'
cfg.TRAINER.SCHEDULER_INTERVAL = 'step'
cfg.TRAINER.CANONICAL_LR = 8e-4
cfg.TRAINER.WARMUP_STEP = 512
cfg.TRAINER.WARMUP_RATIO = 0.1

# pose estimation
cfg.TRAINER.RANSAC_PIXEL_THR = 0.5
cfg.TRAINER.FREEZE_MATCHER = True
cfg.TRAINER.OPTIMIZER = "adamw"
cfg.TRAINER.ADAMW_DECAY = 0.1

cfg.LOFTR.LOSS.COARSE_WEIGHT = 0.0
cfg.LOFTR.LOSS.FINE_WEIGHT = 0.0
cfg.LOFTR.LOSS.COARSE_POSE_WEIGHT = 0.0
cfg.LOFTR.LOSS.FINE_POSE_WEIGHT = 0.0
cfg.LOFTR.LOSS.COARSE_IRLS_WEIGHT = 0.0
cfg.LOFTR.LOSS.FINE_IRLS_WEIGHT = 1.0
cfg.LOFTR.LOSS.COARSE_POSE_TYPE = 'cosine'
cfg.LOFTR.LOSS.FINE_POSE_TYPE = 'cosine'
cfg.LOFTR.LOSS.ROTATION_WEIGHT = 1.0
cfg.LOFTR.LOSS.ANGULAR_LOSS = True

cfg.FUNDAMENTAL_MATRIX.P = 0.5
cfg.FUNDAMENTAL_MATRIX.COMPUTE_FINE = True
cfg.FUNDAMENTAL_MATRIX.ROBUST_ESTIMATOR_TYPE = 'IRLS'
