from src.config.default import _CN as cfg

cfg.LOFTR.MATCH_COARSE.MATCH_TYPE = 'dual_softmax'
cfg.LOFTR.MATCH_COARSE.TRAIN_COARSE_PERCENT = 1.0 # default value is 0.2
cfg.LOFTR.MATCH_COARSE.SPARSE_SPVS = False

#cfg.TRAINER.MSLR_MILESTONES = [3, 6, 9, 12, 17, 20, 23, 26, 29]
cfg.TRAINER.CANONICAL_LR = 8e-5
cfg.TRAINER.SCHEDULER = 'ExponentialLR'
cfg.TRAINER.SCHEDULER_INTERVAL = 'step'
cfg.TRAINER.WARMUP_STEP = 512  # 3 epochs
cfg.TRAINER.WARMUP_RATIO = 0.1

cfg.TRAINER.FREEZE_MATCHER = False

cfg.LOFTR.LOSS.COARSE_WEIGHT = 1.0
cfg.LOFTR.LOSS.FINE_WEIGHT = 1.0
cfg.LOFTR.LOSS.COARSE_POSE_WEIGHT = 0.0
cfg.LOFTR.LOSS.FINE_POSE_WEIGHT = 0.0
cfg.LOFTR.LOSS.COARSE_IRLS_WEIGHT = 0.0
cfg.LOFTR.LOSS.FINE_IRLS_WEIGHT = 1.0
cfg.LOFTR.LOSS.COARSE_POSE_TYPE = 'cosine'
cfg.LOFTR.LOSS.FINE_POSE_TYPE = 'cosine'
cfg.LOFTR.LOSS.ROTATION_WEIGHT = 1.0
cfg.LOFTR.LOSS.ANGULAR_LOSS = True

cfg.FUNDAMENTAL_MATRIX.COMPUTE_FINE = True
cfg.FUNDAMENTAL_MATRIX.ROBUST_ESTIMATOR_TYPE = 'LIRLS'